name: project_environment
dependencies:
- python=3.6.2
- pip:
  - azureml-core==1.24.0
  - azureml-defaults==1.24.0
  - azureml-telemetry==1.24.0
  - azureml-train-core==1.24.0
  - azureml-widgets==1.24.0
  - azureml-sdk==1.24.0
  - azureml-train-automl-runtime==1.24.0
  - azureml-automl-runtime==1.24.0
  - mlflow
  - sklearn-pandas
- pandas
- numpy
- tqdm
- py-xgboost
- joblib
- xgboost
- scikit-learn==0.22.1
- matplotlib
channels:
- anaconda
- conda-forge